version: '3.3'

services:
  tomcat:
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:8080
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EXAMPLE_DB_NAME
    ports:
      - 5432:5432